apiVersion: v1
kind: Secret
metadata:
  name: private-repo-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:yourusername/test-argo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    Lp41cSFv6FXBsAAAAYYWRhbGJlcnRiYXJ0YUBvdXRiaXguY29tAQID
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"
  enableLfs: "false"