apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:youryusername/test-argo.git
    targetRevision: main
    path: helm
    directory:
         recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: destination-net
  syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            prune: false
            selfHeal: false

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:youryusername/test-argo2.git
    targetRevision: main
    path: helm
    directory:
         recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: destination-net
  syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            prune: false
            selfHeal: false